#!/usr/bin/env bash
# Manage the manage_my_process daemon

PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

start_process() {
    "$PROCESS" &
    echo $! > "$PIDFILE"

    if [ "$1" != "quiet" ]; then
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        kill "$pid"

        while kill -0 "$pid" 2>/dev/null
        do
            sleep 1
        done

        rm -f "$PIDFILE"
    fi

    if [ "$1" != "quiet" ]; then
        echo "manage_my_process stopped"
    fi
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        stop_process quiet
        start_process quiet
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
